### ISSUE TITLE
[BUG] - Failed to create an encrypted shareable link for the document/image

### ISSUE THREAD

**Issue by ghost** [SouthbankSoftware/provendocs#109]
**Describe the bug**

**To Reproduce**
1. Go to 'documents'
2. Click on 'image'
3. Scroll down to 'share link'
4. Fails to create an encrypted shareable link to the image

**Expected behavior**
receive a shareable link to use to create NFTs

**Screenshots**

**Environment (please complete the following information):**
 - Browser [firefox, brave]
 - Version [92]

**Additional context**

**Comment by ghost** [comment]
The nature of the issue is 404 error.

**Comment by michaeljharrison** [comment]
Hi there,

Thanks for raising this bug, I've pushed a hotfix, see https://provendb.readme.io/discuss/613e34f97895d30127ad9d87 for more details.
